<?php

namespace Fabiang\Xmpp\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-31 at 20:01:01.
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Event
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new Event;
    }

    /**
     * Test setting and getting name.
     *
     * @covers Fabiang\Xmpp\Event\Event::getName
     * @covers Fabiang\Xmpp\Event\Event::setName
     * @return void
     */
    public function testSetAndGetName()
    {
        $this->assertSame('1', $this->object->setName(1)->getName());
    }

    /**
     * Test setting and getting target.
     *
     * @covers Fabiang\Xmpp\Event\Event::getTarget
     * @covers Fabiang\Xmpp\Event\Event::setTarget
     * @return void
     */
    public function testSetAndGetTarget()
    {
        $target = new \stdClass();
        $this->assertSame($target, $this->object->setTarget($target)->getTarget());
    }

    /**
     * Test setting and getting parameters.
     *
     * @covers Fabiang\Xmpp\Event\Event::getParameters
     * @covers Fabiang\Xmpp\Event\Event::setParameters
     * @return void
     */
    public function testGetParameters()
    {
        $params = array(1, 2, 3);
        $this->assertSame($params, $this->object->setParameters($params)->getParameters());
    }

    /**
     * Test setting and getting event stack.
     *
     * @covers Fabiang\Xmpp\Event\Event::getEventStack
     * @covers Fabiang\Xmpp\Event\Event::setEventStack
     * @return void
     */
    public function testSetAndGetEventStack()
    {
        $stack = array(function() {

        });
        $this->assertSame($stack, $this->object->setEventStack($stack)->getEventStack());
    }
    
    /**
     * Test getting parameter by index.
     * 
     * @covers Fabiang\Xmpp\Event\Event::getParameter
     * @return void
     */
    public function testGetParameter()
    {
        $this->object->setParameters(array(1, 2, 3));
        $this->assertSame(1, $this->object->getParameter(0));
        $this->assertSame(2, $this->object->getParameter(1));
        $this->assertSame(3, $this->object->getParameter(2));
    }
    
    /**
     * Test getting parameter by missing index.
     * 
     * @covers Fabiang\Xmpp\Event\Event::getParameter
     * @expectedException \Fabiang\Xmpp\Exception\OutOfRangeException
     * @return void
     */
    public function testGetParameterNotSet()
    {
        $this->object->getParameter(0);
    }
    
    /**
     * Test getting parameter by missing index.
     * 
     * @covers Fabiang\Xmpp\Event\Event::getParameter
     * @expectedException \Fabiang\Xmpp\Exception\InvalidArgumentException
     * @return void
     */
    public function testGetParameterIbvalidType()
    {
        $this->object->getParameter('test');
    }

}
