<?php
namespace Fabiang\Xmpp\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-11 at 18:21:21.
 */
class XMLEventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XMLEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * 
     * @return void
     */
    protected function setUp()
    {
        $this->object = new XMLEvent;
    }

    /**
     * Test setting and checking is start tag.
     * 
     * @covers Fabiang\Xmpp\Event\XMLEvent::isStartTag
     * @covers Fabiang\Xmpp\Event\XMLEvent::setStartTag
     * @return void
     */
    public function testSetAndIsStartTag()
    {
        $this->assertFalse($this->object->isStartTag());
        $this->assertTrue($this->object->setStartTag(true)->isStartTag());
    }
}
