<?php

namespace Fabiang\Xmpp\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-17 at 11:09:05.
 */
class XMLParserExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Test creation of exception.
     * 
     * @covers Fabiang\Xmpp\Exception\XMLParserException::create
     * @return void
     */
    public function testCreate()
    {
        $parser = xml_parser_create();
        $this->assertSame(0, xml_parse($parser, "<?xml version=\"1.0\" ?>\n<xml>\n<test<></xml>"));
        
        $exception = XMLParserException::create($parser);
        $this->assertSame('XML parsing error: "> required" at Line 3 at column 6', $exception->getMessage());
    }
    
    /**
     * Test if no resource instance is given.
     * 
     * @covers Fabiang\Xmpp\Exception\XMLParserException::create
     * @expectedException Fabiang\Xmpp\Exception\InvalidArgumentException
     * @return void
     */
    public function testCreateNoResourceInstance()
    {
        XMLParserException::create('test');
    }
    
    /**
     * Test if resource is no xml parser instance.
     * 
     * @covers Fabiang\Xmpp\Exception\XMLParserException::create
     * @expectedException Fabiang\Xmpp\Exception\InvalidArgumentException
     * @return void
     */
    public function testCreateNoXMLResourceInstance()
    {
        $handle = fopen('php://memory', 'r');
        try {
            XMLParserException::create($handle);
        } catch (\Exception $e) {
            fclose($handle);
            throw $e;
        }
    }

}
