<?php
namespace Fabiang\Xmpp\Protocol;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-11 at 18:43:49.
 */
class StreamTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Stream
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * 
     * @return void
     */
    protected function setUp()
    {
        $this->object = new Stream;
    }

    /**
     * Test turning object into array.
     * 
     * @covers Fabiang\Xmpp\Protocol\Stream::toString
     * @return void
     */
    public function testToString()
    {
        $this->object->setTo('foobar');
        $this->assertSame(
            '<stream:stream to="foobar" xmlns:stream="http://etherx.jabber.org/streams"'
            . ' xmlns="jabber:client" version="1.0">',
            $this->object->toString()
        );
    }

    /**
     * Test setting and getting to.
     * 
     * @covers Fabiang\Xmpp\Protocol\Stream::getTo
     * @covers Fabiang\Xmpp\Protocol\Stream::setTo
     * @return void
     */
    public function testSetAndGetTo()
    {
        $this->assertSame('1', $this->object->setTo(1)->getTo());
    }

}
